apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freezo.fullname" . }}-frontend
  labels:
    {{- include "freezo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "freezo.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "freezo.frontendSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
