apiVersion: v1
kind: Service
metadata:
  name: {{ include "freezo.fullname" . }}-frontend
  labels:
    {{- include "freezo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "freezo.frontendSelectorLabels" . | nindent 4 }}
