apiVersion: v1
kind: Service
metadata:
  name: {{ include "freezo.fullname" . }}-backend
  labels:
    {{- include "freezo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "freezo.backendSelectorLabels" . | nindent 4 }}
